Refactor/require to revert
rsksmart/rns-partner-registrar pull request #68
Opened 2023-02-09 23:26 UTC by LordCheta

This PR aims to introduce more gas savings by using reverts instead of require statements

2023-02-16 10:31 UTC, OnyekaIjeh requested changes

2023-02-16 10:31 UTC, OnyekaIjeh commented on contracts/Registrar/PartnerRegistrar.sol
> +        if (_commitmentRevealTime[commitment] > 1) {
This should be `> 0`

2023-02-16 13:28 UTC, LordCheta commented on contracts/Registrar/PartnerRegistrar.sol
> +        if (_commitmentRevealTime[commitment] > 1) {
Thanks for catching that

2023-02-16 16:04 UTC, sergio-jara approved these changes
nice. love this PR. by removing the require statements we can actually tell if our tests are covering these edge cases.

2023-02-21 17:04 UTC, OnyekaIjeh approved these changes

2023-02-22 09:02 UTC, merged